<?php

/**
* Implements hook_entity_view_alter().
*/
function unset_html_head_link_entity_view_alter(array &$build, Drupal\Core\Entity\EntityInterface $entity, \Drupal\Core\Entity\Display\EntityViewDisplayInterface $display) {
  // Cheking view_mode for node.
  if ($build['#view_mode'] === 'full' && $entity Instanceof \Drupal\node\NodeInterface) {
    // Cheking html_head_link on attached tags in head.
    if (!isset($build['#attached']['html_head_link'])) return;
    // Array to unset.
    // Also, you may unset any head links you want (like rel="canonical" or rel="shortlink").
    $unset_html_head_link = [      
      'delete-form',
      'edit-form',
      'version-history',
      'revision'
    ];
    // Unset loop.
    foreach ($build['#attached']['html_head_link'] as $key => $value) {
      if (isset($value[0]['rel']) && in_array($value[0]['rel'], $unset_html_head_link)) unset($build['#attached']['html_head_link'][$key]);
    }
  }
}
